### ISSUE TITLE
link to English addon page

### ISSUE THREAD

**Issue by brabalan** [passB/passB#34]
The current link from https://passb.github.io/ to the addon page is to https://addons.mozilla.org/de/firefox/addon/passb/. Could you link to https://addons.mozilla.org/en-US/firefox/addon/passb/ instead?

**Comment by phryneas** [comment]
Absolutely, I missed that. I'll fix that immediately. Thanks for the catch!

**Comment by phryneas** [comment]
I fixed it to the language-agnostic https://addons.mozilla.org/firefox/addon/passb/ - could you please verify that thats working for you?

**Comment by brabalan** [comment]
It's working great, thanks!
